baseURL: "https://oliviatrager.github.io/"
title: Olivia Trager
paginate: 5
theme: "PaperMod"

defaultContentLanguage: "de"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

languages:
  de:
    languageName: "Deutsch"
    weight: 1
    taxonomies:
      category: kategorien
      tag: schlagworte
      series: serien
    menu:
      main:
        - name: Archiv
          url: archives/
          weight: 5
        - name: Suche
          url: search/
          weight: 10
        - name: Schlagworte
          url: tags/
          weight: 10
        - name: Über mich
          url: about/
          weight: 10
        - name: GitHub
          url: https://github.com/

  en:
    languageName: "English"
    weight: 2
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: About
          url: about/
          weight: 10
        - name: GitHub
          url: https://github.com/

  fr:
    languageName: "Français"
    weight: 3
    taxonomies:
      category: catégories
      tag: mots-clés
      series: séries
    profileMode:
      enabled: true
      title: Olivia Trager
      imageUrl: "<image link>"
      imageTitle: "Photo de profil"
      buttons:
        - name: Archive
          url: "/archive"
        - name: GitHub
          url: "https://github.com/"

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Olivia Trager's Website"
  author: Olivia Trager

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true

socialIcons:
  - name: github
    url: "https://github.com/oliviatrager"
  - name: twitter
    url: "https://twitter.com/oliviatrager"

editPost:
  URL: "https://github.com/oliviatrager/website/tree/main/content"
  Text: "Suggest Changes"
  appendFilePath: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
