baseURL: https://oliviatrager.github.io
languageCode: en-us
title: Olivia Trager
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true
defaultContentLanguage: de

languages:
      de:
        title: Olivia Trager
        languageName: Deutsch
        weight: 1
        taxonomies:
          tag: "Tags"
          category: "Kategorien"
        menu:
          main:
            - name: Home
              url: /
            - name: Blog
              url: posts
            - name: Über mich
              url: about
            - name: Kontakt
              url: contact
        
         

      en:
        title: Olivia Trager
        languageName: ":us:"
        weight: 2


      fr:
        languageName: ":fr:"
        languageAltTitle: French
        weight: 2
        title: Olivia Trager
        profileMode:
            enabled: true
            title: Olivia Trager
            imageUrl: "https://github.com/OliviaTrager/oliviatrager.github.io/blob/main/oliviatrager.github.io/resources/_gen/images/profile.jpg?raw=true"
            imageTitle: ProfileMode image
            # imageWidth: 120
            # imageHeight: 120
            subtitle: "Votre avocat en immigration de confiance à Berlin"
            buttons:
                - name: Email
                  url: mailto:renekuhn@posteo.de
      #hebrew:
      he:
        title: Olivia Trager
        weight: 4
        languageName: ":hb:"
        languageAltTitle: Hebrew
        
        profileMode:
            enabled: true
            title: Olivia Trager
            imageUrl: "https://github.com/OliviaTrager/oliviatrager.github.io/blob/main/oliviatrager.github.io/resources/_gen/images/profile.jpg?raw=true"
            imageTitle: ProfileMode image
            # imageWidth: 120
            # imageHeight: 120
            subtitle: "העורך דין להגירה האמין שלך בברלין"
            buttons:
                - name: Blog
                  url: posts
                - name: Email
                  url: mailto:renekuhn@posteo.de